---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set registry http://registry.npmjs.org/
  - npm config set spin false
  - npm install -g bower
  - npm install -g gulp-cli
  - npm install -g gulp
  - git config user.name 'travis-build'
  - bower --version
  - npm install phantomjs-prebuilt@2
  - phantomjs --version

install:
  - npm install
  - bower install

script:
  - ember test
